Fix: Broken QR code due to oklch()
ProgSoc/ClubVotingSystem pull request #31
Opened 2024-10-22 12:23 UTC by VanillaViking

The QR Code breaks due to `getComputedStyle()` returning a colour in oklch() colour space rather than rgb. 

Fix: convert any oklch() colours to rgb. I couldn't find any package that did the conversion for me, therefore added my own conversion function in utils.

Fixes #30

2024-10-22 20:15 UTC, sebasptsch approved these changes

2024-10-22 20:15 UTC, arduano requested changes
Are you sure this is a good solution? If we decide to use a new style sometime, it might just randomly break if they use something else like HSL or any other css function.

As I suggested in the issue, it's probably best to use a library like `color-parse` that seems to have implemented everything already. And it seems like you've added the library, but haven't included it in the actual code?

2024-10-22 20:17 UTC, arduano commented
Oh also just a cool github feature but you can do this:

Fixes #30

the word "fixes" automatically gets detected by github and links the issue to the PR, making the issue close when the PR gets merged

2024-10-23 20:12 UTC, arduano approved these changes

2024-10-23 21:07 UTC, merged